In [1]:
import pandas as pd

# Human Data

In [2]:
df1 = pd.read_csv("../data/iowa_human/combined_igt_human.csv")

In [3]:
df1

,experiment,session_id,trial_number,choice,won,loss,total,variant
0,1,0,1,H,100.0,-200.0,1900.0,1
1,1,0,2,H,100.0,-150.0,1850.0,1
2,1,0,3,V,100.0,-0.0,1950.0,1
3,1,0,4,D,50.0,-250.0,1750.0,1
4,1,0,5,J,50.0,-0.0,1800.0,1
...,...,...,...,...,...,...,...,...
55430,1,463,96,M,50.0,-0.0,1825.0,3
55431,1,463,97,N,100.0,-0.0,1925.0,3
55432,1,463,98,N,100.0,-0.0,2025.0,3
55433,1,463,99,N,100.0,-0.0,2125.0,3
55434,1,463,100,M,50.0,-0.0,2175.0,3

In [4]:
df1.shape

(55435, 8)

In [5]:
df1.groupby("variant")["session_id"].count()

variant
1    15900
2    36635
3     2900
Name: session_id, dtype: int64

### Checking for missing sessions and trials

In [6]:
human_grouped_by_variant_session = df1.groupby(['variant', 'session_id']).agg(
    num_trials=('trial_number', 'count')
).reset_index()

human_grouped_by_variant_session.head()

   variant  session_id  num_trials
0        1           0         100
1        1           1         100
2        1           2         100
3        1           3         100
4        1           4         100

In [7]:
# For Variant 1:
human_variant1_sessions = human_grouped_by_variant_session[human_grouped_by_variant_session['variant'] == 1]
human_unique_sessions_v1 = human_variant1_sessions['session_id'].nunique()
human_trials_per_session_v1 = human_variant1_sessions['num_trials'].value_counts().reset_index()
human_trials_per_session_v1.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 1: {human_unique_sessions_v1}")
print(f"Distribution of trials per session in Variant 1:\n{human_trials_per_session_v1}")

Number of unique sessions in Variant 1: 159
Distribution of trials per session in Variant 1:
   num_trials  count
0         100    159

In [8]:
# For Variant 2
human_grouped_by_exp_variant_session = df1.groupby(['experiment', 'variant', 'session_id']).size().reset_index(name='num_trials')

human_variant2_sessions = human_grouped_by_exp_variant_session[human_grouped_by_exp_variant_session['variant'] == 2]
human_unique_sessions_v2 = human_variant2_sessions.shape[0]
human_trials_per_session_v2 = human_variant2_sessions['num_trials'].value_counts().reset_index()
human_trials_per_session_v2.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 2: {human_unique_sessions_v2}")
print(f"Distribution of trials per session in Variant 2:\n{human_trials_per_session_v2}")

Number of unique sessions in Variant 2: 323
Distribution of trials per session in Variant 2:
   num_trials  count
0         100    222
1         150     88
2          95     13

In [9]:
# For Variant 3:
human_variant3_sessions = human_grouped_by_variant_session[human_grouped_by_variant_session['variant'] == 3]
human_unique_sessions_v3 = human_variant3_sessions['session_id'].nunique()
human_trials_per_session_v3 = human_variant3_sessions['num_trials'].value_counts().reset_index()
human_trials_per_session_v3.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 3: {human_unique_sessions_v3}")
print(f"Distribution of trials per session in Variant 3:\n{human_trials_per_session_v3}")

Number of unique sessions in Variant 3: 29
Distribution of trials per session in Variant 3:
   num_trials  count
0         100     29

### Checking for missing values and duplicates

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55435 entries, 0 to 55434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   experiment    55435 non-null  int64
 1   session_id    55435 non-null  int64
 2   trial_number  55435 non-null  int64
 3   choice        55435 non-null  object
 4   won           55435 non-null  float64
 5   loss          55435 non-null  float64
 6   total         55435 non-null  float64
 7   variant       55435 non-null  int64
dtypes: float64(3), int64(4), object(1)
memory usage: 3.4+ MB

In [11]:
df1.duplicated().sum()

np.int64(0)

#

# Deepseek Data

In [12]:
df2 = pd.read_csv("../data/iowa_models/deepseek/deepseek_igt_combined.csv")

In [13]:
df2

,session_id,trial_number,choice,won,loss,total,variant,model
0,1,1,K,100.0,0.0,2100.0,1,deepseek
1,1,2,K,100.0,0.0,2200.0,1,deepseek
2,1,3,K,100.0,0.0,2300.0,1,deepseek
3,1,4,K,100.0,0.0,2400.0,1,deepseek
4,1,5,K,100.0,-1250.0,1250.0,1,deepseek
...,...,...,...,...,...,...,...,...
44995,50,96,Q,100.0,0.0,-1000.0,3,deepseek
44996,50,97,Q,100.0,-250.0,-1150.0,3,deepseek
44997,50,98,K,100.0,-1250.0,-2300.0,3,deepseek
44998,50,99,Q,100.0,-250.0,-2450.0,3,deepseek
44999,50,100,Q,100.0,-250.0,-2600.0,3,deepseek

In [14]:
df2.shape

(45000, 8)

In [15]:
df2.groupby("variant")["session_id"].count()

variant
1    20000
2    20000
3     5000
Name: session_id, dtype: int64

### Checking for missing sessions and trials

In [16]:
deepseek_grouped_by_variant_session = df2.groupby(['variant', 'session_id']).agg(
    num_trials=('trial_number', 'count')
).reset_index()

deepseek_grouped_by_variant_session.head()

   variant  session_id  num_trials
0        1           1         100
1        1           2         100
2        1           3         100
3        1           4         100
4        1           5         100

In [17]:
# For Variant 1:
deepseek_variant1_sessions = deepseek_grouped_by_variant_session[deepseek_grouped_by_variant_session['variant'] == 1]
deepseek_unique_sessions_v1 = deepseek_variant1_sessions['session_id'].nunique()
deepseek_trials_per_session_v1 = deepseek_variant1_sessions['num_trials'].value_counts().reset_index()
deepseek_trials_per_session_v1.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 1: {deepseek_unique_sessions_v1}")
print(f"Distribution of trials per session in Variant 1:\n{deepseek_trials_per_session_v1}")

Number of unique sessions in Variant 1: 200
Distribution of trials per session in Variant 1:
   num_trials  count
0         100    200

In [18]:
# For Variant 2:
deepseek_variant2_sessions = deepseek_grouped_by_variant_session[deepseek_grouped_by_variant_session['variant'] == 2]
deepseek_unique_sessions_v2 = deepseek_variant2_sessions['session_id'].nunique()
deepseek_trials_per_session_v2 = deepseek_variant2_sessions['num_trials'].value_counts().reset_index()
deepseek_trials_per_session_v2.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 2: {deepseek_unique_sessions_v2}")
print(f"Distribution of trials per session in Variant 2:\n{deepseek_trials_per_session_v2}")

Number of unique sessions in Variant 2: 200
Distribution of trials per session in Variant 2:
   num_trials  count
0         100    200

In [19]:
# For Variant 3:
deepseek_variant3_sessions = deepseek_grouped_by_variant_session[deepseek_grouped_by_variant_session['variant'] == 3]
deepseek_unique_sessions_v3 = deepseek_variant3_sessions['session_id'].nunique()
deepseek_trials_per_session_v3 = deepseek_variant3_sessions['num_trials'].value_counts().reset_index()
deepseek_trials_per_session_v3.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 3: {deepseek_unique_sessions_v3}")
print(f"Distribution of trials per session in Variant 3:\n{deepseek_trials_per_session_v3}")

Number of unique sessions in Variant 3: 50
Distribution of trials per session in Variant 3:
   num_trials  count
0         100     50

### Checking for missing values and duplicates

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   session_id    45000 non-null  int64
 1   trial_number  45000 non-null  int64
 2   choice        45000 non-null  object
 3   won           45000 non-null  float64
 4   loss          45000 non-null  float64
 5   total         45000 non-null  float64
 6   variant       45000 non-null  int64
 7   model         45000 non-null  object
dtypes: float64(3), int64(3), object(2)
memory usage: 2.7+ MB

In [21]:
df2.duplicated().sum()

np.int64(0)

#

# Gemini Data

In [22]:
df3 = pd.read_csv("../data/iowa_models/gemini/gemini_igt_combined.csv")

In [23]:
df3

       session_id  trial_number choice  won  loss  total  variant   model
0               1             1      Q  100  -250   1850        1  gemini
1               1             2      K  100     0   1950        1  gemini
2               1             3      S   50     0   2000        1  gemini
3               1             4      D   50     0   2050        1  gemini
4               1             5      K  100     0   2150        1  gemini
...           ...           ...    ...  ...   ...    ...      ...     ...
44995          50            96      S   50     0   3000        3  gemini
44996          50            97      S   50   -50   3000        3  gemini
44997          50            98      S   50   -50   3000        3  gemini
44998          50            99      S   50     0   3050        3  gemini
44999          50           100      S   50     0   3100        3  gemini

[45000 rows x 8 columns]

In [24]:
df3.shape

(45000, 8)

In [25]:
df3.groupby("variant")["session_id"].count()

variant
1    20000
2    20000
3     5000
Name: session_id, dtype: int64

### Checking for missing sessions or trials

In [26]:
gemini_grouped_by_variant_session = df3.groupby(['variant', 'session_id']).agg(
    num_trials=('trial_number', 'count')
).reset_index()

gemini_grouped_by_variant_session.head()

   variant  session_id  num_trials
0        1           1         100
1        1           2         100
2        1           3         100
3        1           4         100
4        1           5         100

In [27]:
# For Variant 1:
gemini_variant1_sessions = gemini_grouped_by_variant_session[gemini_grouped_by_variant_session['variant'] == 1]
gemini_unique_sessions_v1 = gemini_variant1_sessions['session_id'].nunique()
gemini_trials_per_session_v1 = gemini_variant1_sessions['num_trials'].value_counts().reset_index()
gemini_trials_per_session_v1.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 1: {gemini_unique_sessions_v1}")
print(f"Distribution of trials per session in Variant 1:\n{gemini_trials_per_session_v1}")

Number of unique sessions in Variant 1: 200
Distribution of trials per session in Variant 1:
   num_trials  count
0         100    200

In [28]:
# For Variant 2:
gemini_variant2_sessions = gemini_grouped_by_variant_session[gemini_grouped_by_variant_session['variant'] == 2]
gemini_unique_sessions_v2 = gemini_variant2_sessions['session_id'].nunique()
gemini_trials_per_session_v2 = gemini_variant2_sessions['num_trials'].value_counts().reset_index()
gemini_trials_per_session_v2.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 2: {gemini_unique_sessions_v2}")
print(f"Distribution of trials per session in Variant 2:\n{gemini_trials_per_session_v2}")

Number of unique sessions in Variant 2: 200
Distribution of trials per session in Variant 2:
   num_trials  count
0         100    200

In [29]:
# For Variant 3:
gemini_variant3_sessions = gemini_grouped_by_variant_session[gemini_grouped_by_variant_session['variant'] == 3]
gemini_unique_sessions_v3 = gemini_variant3_sessions['session_id'].nunique()
gemini_trials_per_session_v3 = gemini_variant3_sessions['num_trials'].value_counts().reset_index()
gemini_trials_per_session_v3.columns = ['num_trials', 'count']

print(f"Number of unique sessions in Variant 3: {gemini_unique_sessions_v3}")
print(f"Distribution of trials per session in Variant 3:\n{gemini_trials_per_session_v3}")

Number of unique sessions in Variant 3: 50
Distribution of trials per session in Variant 3:
   num_trials  count
0         100     50

### Checking for missing values and duplicates

In [30]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   session_id    45000 non-null  int64
 1   trial_number  45000 non-null  int64
 2   choice        45000 non-null  object
 3   won           45000 non-null  int64
 4   loss          45000 non-null  int64
 5   total         45000 non-null  int64
 6   variant       45000 non-null  int64
 7   model         45000 non-null  object
dtypes: int64(6), object(2)
memory usage: 2.7+ MB

In [31]:
df3.duplicated().sum()

np.int64(0)